name: deployment

on:
  push:
    branches: [ master ]

jobs:

  quality:
    name: Code Rewier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: 📦 Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: 📥 Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: 📥 Install dependencies
        run: |
          poetry install --no-interaction --no-root
          poetry install --no-interaction

      - name: Run Black (formatting)
        run: poetry run black --check src/ tests/ log_analyzer.py

      - name: Run isort (imports)
        run: poetry run isort --check-only src/ tests/ log_analyzer.py

      - name: Run flake8 (linting)
        run: poetry run flake8 src/ tests/ log_analyzer.py

      - name: Run mypy (type checking)
        run: poetry run mypy src/ tests/ log_analyzer.py

  test:
    name: run test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
          poetry install --no-interaction

      - name: Run pre-commit hooks
        run: poetry run pre-commit run --all-files

      - name: Run tests
        run: poetry run pytest -v